---
# This is the soluble cli workflow with actions
on: [push]  # yamllint disable-line rule:truthy
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: yamllint
        uses: docker://ghcr.io/ffurrer2/yamllint:latest
        with:
          args: '--format standard .'
        # yamllint disable
        # run: docker run --tty --volume $(pwd):/tf --workdir /tf bridgecrew/checkov --config-file /tf/config/checkov_config.yaml
        # yamllint enable
